#!/usr/bin/env python3
"""Regenerate the track/card landing block in index.md from `paper_section` frontmatter.

Tracks follow the EMM review's outline. A page joins a track by declaring
`paper_section: ["3.1", ...]` in its frontmatter; the block between the
landing markers in index.md is rewritten on every run.

Usage: tools/build-landing.py          # rewrite index.md
       tools/build-landing.py --check  # exit 1 if index.md is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI_DIRS = ["20-Entities", "30-Concepts", "40-Topics", "50-Notes"]
START, END = "<!-- landing:start -->", "<!-- landing:end -->"

# (track heading, one-line intro, [(paper_section code, group title)])
TRACKS = [
    ("§2 Conceptual framework — the locus state",
     "What a locus state is, which layers make it up, and why mosaicism needs it.",
     [("2", "Locus state & layers")]),
    ("§3 Measurement — five DNA layers",
     "How each layer is read from a single cell's one copy of DNA.",
     [("3.1", "Genotype"),
      ("3.2", "Chromatin accessibility"),
      ("3.2.1", "Chromatin accessibility › Fiber-seq & single-molecule"),
      ("3.3", "DNA methylation"),
      ("3.4", "Histone modification"),
      ("3.5", "3D genome")]),
    ("§4 Computational framework",
     "From per-layer inference to cross-layer integration.",
     [("4.1", "Single-cell variant calling"),
      ("4.2", "Single-modality preprocessing & analysis"),
      ("4.3", "Multimodal integration"),
      ("4.4", "Sequence-based prediction & foundation models"),
      ("4.5", "Locus-state inference")]),
    ("§5 Applications",
     "Where single-cell DNA layers answer biological questions.",
     [("5.1", "Cancer clonal architecture"),
      ("5.2", "Brain somatic mosaicism"),
      ("5.3", "Clonal hematopoiesis & aging"),
      ("5.4", "Development & lineage tracing")]),
    ("§6–7 Limitations & future",
     "Open tensions, and the syntheses still to be written.",
     [("6", "Limitations & open questions"),
      ("7", "Future directions")]),
    ("Appendix",
     "Pages about how this wiki itself is built.",
     [("A", "Wiki tooling")]),
]

LABELS = {"topic": "hub", "note": "synthesis", "concept": "concept", "entity": "entity"}


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    return (m.group(1), text[m.end():]) if m else ("", text)


def field(fm, key):
    m = re.search(rf"^{key}:\s*(.+)$", fm, re.M)
    return m.group(1).strip().strip("\"'") if m else None


def sections(fm):
    raw = field(fm, "paper_section")
    return re.findall(r"[\w.]+", raw) if raw else []


def first_sentence(body):
    for line in body.splitlines():
        line = line.strip().lstrip(">").strip()
        if not line or line.startswith(("#", "|", "---", "!", "<", "```")):
            continue
        line = re.sub(r"\(\[\[[^\]]*\]\][^)]*\)", "", line)        # citation parens
        line = re.sub(r"\[\[([^\]|]*\|)?([^\]]*)\]\]", r"\2", line)  # wikilinks
        line = re.sub(r"[*`_]|\(synthesis\)", "", line).strip()
        line = re.sub(r"\s+([.,;:])", r"\1", line)
        line = re.split(r"(?<=[.!?])\s", line)[0]
        if len(line) < 40:  # status stamps, labels — not a definition
            continue
        return line if len(line) <= 160 else line[:157].rstrip() + "…"
    return ""


def paper_count(body, summaries):
    links = {t.split("/")[-1] for t in re.findall(r"\[\[([^\]|#]+)", body)}
    return len(links & summaries)


def collect():
    summaries = {p.stem for p in (ROOT / "10-Summaries").glob("*.md")}
    cards = {}
    for d in WIKI_DIRS:
        for path in sorted((ROOT / d).glob("*.md")):
            fm, body = frontmatter(path.read_text())
            for code in sections(fm):
                cards.setdefault(code, []).append({
                    "slug": f"{d}/{path.stem}",
                    # "/" in a wikilink alias is read as a path by Quartz; use U+2215
                    "title": (field(fm, "title") or path.stem).replace("/", "∕"),
                    "label": LABELS.get(field(fm, "type"), field(fm, "type") or "page"),
                    "desc": field(fm, "description") or first_sentence(body),
                    "papers": paper_count(body, summaries),
                })
    return cards


def render(cards):
    known = {code for _, _, groups in TRACKS for code, _ in groups}
    unknown = sorted(set(cards) - known)
    if unknown:
        sys.exit(f"unknown paper_section codes: {unknown}")
    out = [START, "<!-- generated by tools/build-landing.py; edit paper_section frontmatter, not this block -->", ""]
    for heading, intro, groups in TRACKS:
        out += [f"### {heading}", "", intro, ""]
        for code, title in groups:
            out.append(f"> [!cards] {title}")
            items = sorted(cards.get(code, []), key=lambda c: (c["label"] != "hub", c["title"].lower()))
            if not items:
                out.append("> - `in progress` No hub page yet — candidate for a new topic page.")
            for c in items:
                n = c["papers"]
                meta = f" · {n} paper{'s' if n > 1 else ''}" if n else ""
                out.append(f"> - `{c['label']}{meta}` [[{c['slug']}|{c['title']}]] — {c['desc']}")
            out.append("")
    out.append(END)
    return "\n".join(out)


def main():
    index = ROOT / "index.md"
    text = index.read_text()
    if START not in text or END not in text:
        sys.exit(f"index.md is missing the {START} / {END} markers")
    block = render(collect())
    new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    if "--check" in sys.argv:
        sys.exit(0 if new == text else "index.md landing block is stale; run tools/build-landing.py")
    index.write_text(new)
    print("index.md landing block rewritten")


if __name__ == "__main__":
    main()
